### ISSUE TITLE
Probleme with submenu

### ISSUE THREAD

**Issue by dooclock** [pmoreno-rodriguez/grav-theme-editorial#16]
Why when you add content to the root level of the pages it is not displayed ?

For example here :
http://editorial.juanvillen.es/
the submenu only display sub page not the page itself 
<img width="476" alt="Firefox_Screenshot_2023-04-18T09-09-42 481Z" src="https://user-images.githubusercontent.com/6494825/232730419-81bafcf9-f946-43bd-9a9f-0b773c4d1c30.png">

**Comment by pmoreno-rodriguez** [comment]
Hi @dooclock 
If you take a look at the navigation.htm.twig file you will see that the behavior of the menu is exactly that, to show the child pages of a parent page, if the dropdown menu option is active. It doesn't make much sense to show the content of that parent page, since its objective is precisely to display the child pages it has in the menu.
However, with a few modifications to the navigation.html.twig file you can achieve your goal.

**Comment by dooclock** [comment]
Hi rodriguez,
Thx for your answer.
I'm just graphic designer  i'm not able to make this hacks. :/

**Comment by pmoreno-rodriguez** [comment]
Both the structure of the theme and the behavior of its elements are the originals of the Editorial theme, from [HTML5Up](https://html5up.net/uploads/demos/editorial/).  The Grav theme is just a transform and almost completely preserves both CSS styles and JavaScript files.
I'll take a look at the behavior of the submenus, but there will almost certainly be modifications to the original JS files.

**Comment by pmoreno-rodriguez** [comment]
Fixed in new version 1.0.8

**Comment by dooclock** [comment]
thx !
