### ISSUE TITLE
HTML code in contact section of sidebar

### ISSUE THREAD

**Issue by learningtime2025** [pmoreno-rodriguez/grav-theme-editorial#41]
Hi, New to GRAV. 
I'm trying to make 2 phone numbers with description.
But i cant get content to looks like i need, i thought to add  `<br>`
But it remains not processed.
How to made html code to work?

or

is it easier to make template for several lines like this?
`+00000000000 - some words, icons`   
`+00000000000 - some words, icons`

where icons can be voice or/and chat for popular messengers.

**Comment by pmoreno-rodriguez** [comment]
Hi @learningtime2025 
As a workaround you could try the following:

In the theme's blueprints.yaml file, in contact.phone:, add the following line, before default value:
`markdown: true`
Then, in the file **partials/contact.html.twig** you can modify **line 14** so that it looks like this:
`<li class="icon solid fa-phone">{{ theme_config.contact.phone|markdown|raw }}</li>`

Try entering this into the phone text box in the admin panel:
`(555) 555-5555 **some words** <br>(555) 555-5555 **some words**`

The result should be like the image I attached.
![editorial01](https://github.com/pmoreno-rodriguez/grav-theme-editorial/assets/60596353/5dd30195-e387-424c-b7d4-ec2970072874)


If you want more customization, please play with the theme code, look for information on markdown and twig in Grav. It's the best way to learn how Grav works and its themes.

**Comment by learningtime2025** [comment]
Excellent!

`<li class="icon solid fa-phone">{{ theme_config.contact.phone|markdown|raw }}</li>`

was enough in my case.

`|markdown|raw`

**Comment by learningtime2025** [comment]
Reopen for copy/paste probably variants before test them:
+  whatsapp chat https://faq.whatsapp.com/5913398998672934/?locale=en_US&category=5245251
