### ISSUE TITLE
Dropdown menu navigation

### ISSUE THREAD

**Issue by imagesoft-ian** [pmoreno-rodriguez/grav-theme-editorial#50]
I have an issue where I have main pages (which has the section introduction) and child pages (details of specific areas) all of the pages are showing fine in the menu but when the main page are only working as if they are 'folders' and do not open the page they relate to they just dropdown to be able to access all the child pages which work perfectly fine and load their details.  

If the main page has no child pages then it is correctly created with the link to the page.

If I tweak the URL to be the main page url the page loads correctly, it appears to be something to do with the way the navigation is created specifically.

**Comment by pmoreno-rodriguez** [comment]
Hi @imagesoft-ian 
I understand that what you want to achieve is that when you click on a menu with children, it can not only be opened to see the child links, but also if it is routable, it can be visited (in its url address).
I have been wanting to make some modification to achieve this for a long time, because the original theme does not have it implemented.
I have created a [new branch](https://github.com/pmoreno-rodriguez/grav-theme-editorial/tree/features), in which I have added some changes to ensure that routable menus can be opened and visited. To do this, if the menu link is routable (it is the default value, it can be changed in the Advanced tab of the page in Admin), it can be clicked and the corresponding page will open, and if you click on the arrow on the right, the corresponding submenu will open.
Could you try this new feature so we can add it to the next version of Editorial?

**Comment by imagesoft-ian** [comment]
Hi @pmoreno-rodriguez 
I have just had a quick look after downloading this branch and it does work, as long as "Dropdown in navbar" is disabled, but I think I will need to have that option enabled due to the number of pages on the site.

**Comment by pmoreno-rodriguez** [comment]
@imagesoft-ian, Now I'm a little confused. Modifications made to the code in `macros.html.twig` are only observed if the dropdown option is enabled.
I don't really understand what the problem is then.
Do you have your site in anywhere online, where I can visit it?

**Comment by imagesoft-ian** [comment]
@pmoreno-rodriguez , You are not the only one, yesterday when I tested it with:
```
dropdown:
  enabled: true
```
set in the config yaml file it did not load the pages, it would only load them if that was

```
dropdown:
  enabled: false
```

today however it is working, maybe something had not refreshed properly in my browser yesterday.

There is an additional issue though with the dropdown menu enabled, when you click a drop down the menu you cannot scroll through the whole list. If you take a look at the "POS terminal" menu you will see what I mean, the url is [](http://www.simplepos.biz/grav-admin).

**Comment by pmoreno-rodriguez** [comment]
> If you take a look at the "POS terminal" menu you will see what I mean, the url is .

What is the URL?

**Comment by imagesoft-ian** [comment]
http://www.simplepos.biz/grav-admin/

**Comment by pmoreno-rodriguez** [comment]
Well @imagesoft-ian, now I could see it in action on the desktop version of the theme, on mobile devices it works fine. I need to review the javascript code to solve this problem.

**Comment by pmoreno-rodriguez** [comment]
Hi @imagesoft-ian , Can you test the new branch [menu](https://github.com/pmoreno-rodriguez/grav-theme-editorial/tree/menu)?

**Comment by pmoreno-rodriguez** [comment]
Added new feature in 2.1.0 version for dropdown menu. See [changelog](https://github.com/pmoreno-rodriguez/grav-theme-editorial/blob/develop/CHANGELOG.md)

Menu branch deleted

**Comment by learningtime2025** [comment]
https://github.com/user-attachments/assets/2eb04182-9c7c-475b-a4eb-a43179e55482

I think that must be fixed.
90% of users will try to clicking on a word, not on the icon.
